{% set name = "jekyll-twitter-plugin" %}
{% set version = "2.1.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: d25ee86813705244dcec3163d9a110a1c0216e157dcf6cf88ab57cf389887acd

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-jekyll >=3.5,<5.0

test:
  requires:
    - rb-jekyll >=3,<4
  commands:
    - ruby -r jekyll -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: A Liquid tag plugin for Jekyll blogging engine that embeds Tweets, Timelines and more from Twitter API.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/rob-murray/{{ name }}

extra:
  recipe-maintainers:
    - bgruening
    - sodre
