travis:
  secure:
    BINSTAR_TOKEN: B46kS6gGGWmjRRXqeKXN2K0YI+CgJrFsK2IOXtfDt1t5Zh7u7gO/LcrZ+qLhzQP3J2xAhDO4dItvlEffBDA3TrLRZ8PTKur3guLh/FGtzfp8hW4HmocLkbMh5CrD1cqAJX8NbpbxxlcsLpxSKARlY+cJDpBuH8/GXxd3iCQrEzI/pPfR89MVtgO+QUTpOk/lAgIriLONwGFagkXqm43iXTWz62myFXqT1SWkHZWAcs6Qw9S+4rA9EDIjF/jEPyiUJr3asMgyPT2zTfqcEigwnsFjPCxU86/4Yp5CtB5sJbtZU5DREysIAAl7tsxAEBf/d3EBiplefqVeYD6q1MbsJ/KE2KHYKQFoyfMOS4wbLPFOXX0JM2zL0LesEmx7cXu3/49RsG341/xkALdqnvawdt1482peZt3FXUl+8eH+QjmC3A6YAE2D180Tn0Ul0J3DMKwZMIHrNNKNroZRVa+8NprCHcM4D5MfxBzR0Js0F2SuaN+HAeE4nSFFADip9HHOgJgX+wM7Xs032gEsOv/t0nsZPnVVHVqgn0P1/WnRStSD+XEz8ABNo/0tvse+pG0hsHJAZwGfbLaG3nX2914LaBLbtHOIBIJOMhA2eHvVn6jV8kY7AI+3NA+eLuTzFC5UmSoKVvlvSTTHBdvxFFp4tXvIx9uJND/+kZOy6PqToZA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
